// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          string `json:"id" gorm:"PRIMARY_KEY;AUTO_INCREMENT;NOT NULL`
	PostID      int    `json:"postID" gorm:"foreignKey:PostID`
	Description string `json:"Description"`
}

type NewComment struct {
	Description string `json:"Description"`
	PostID      int    `json:"postId"`
}

type NewPost struct {
	Title       string        `json:"Title"`
	Content     string        `json:"Content"`
	Author      *string       `json:"Author,omitempty"`
	Hero        *string       `json:"Hero,omitempty"`
	PublishedAt *string       `json:"Published_At,omitempty"`
	UpdatedAt   *string       `json:"Updated_At,omitempty"`
	Comments    []*NewComment `json:"Comments"`
}

type Post struct {
	ID          int        `json:"id" gorm:"PRIMARY_KEY;AUTO_INCREMENT;NOT NULL`
	Title       string     `json:"Title"`
	Content     string     `json:"Content"`
	Author      string     `json:"Author"`
	Hero        string     `json:"Hero"`
	PublishedAt string     `json:"Published_At"`
	UpdatedAt   string     `json:"Updated_At"`
	Comments    []*Comment `json:"Comments,omitempty" gorm:"foreignKey:PostID`
}
